In [3]:
##Importing tensorflow

In [2]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()  # used tf1 here because of assignment requirements


Instructions for updating:
non-resource variables are not supported in the long term


In [54]:
#creating constants

In [7]:
c1 = tf.constant(10)
c2 = tf.constant(14)
c3 = tf.constant("Hello World")

In [ ]:
##Part A - Creating a tensorflow session

In [4]:
sess = tf.Session()

In [8]:
print([c1,c2,c3])

[<tf.Tensor 'Const_2:0' shape=() dtype=int32>, <tf.Tensor 'Const_3:0' shape=() dtype=int32>, <tf.Tensor 'Const_4:0' shape=() dtype=string>]


In [89]:
##Part B - performing operations

Addition = c1+c2
sess.run(Addition)





24

In [78]:
Subtraction = c1-c2
sess.run(Subtraction)

-4

In [ ]:
##Part-C

In [9]:
sess.run(c3)

b'Hello World'

In [10]:
sess.run([c1,c2,c3])

[10, 14, b'Hello World']

In [ ]:
##Part-D - Implementing linear eqaution of a line - y= m*x + c

In [36]:
# when x is a scalar

m = tf.Variable([5], tf.int32)
c= tf.Variable([10], tf.int32)
x = tf.placeholder(tf.int32)
 
y = m*x + c

In [37]:
init = tf.global_variables_initializer()  # for initializing the variables

In [38]:
sess.run(init) # running the init session


In [39]:
##sub-part a.
sess.run(y, feed_dict = {x:7})  #y = mx+c for input scalar x

array([45])

In [40]:
##sub-part b.
sess.run(y, feed_dict = {x:[7,4,5,6,3]}) 

array([45, 30, 35, 40, 25])

In [47]:
##sub-part c. Updating m and c

m1 = tf.assign(m, [7])
c1 = tf.assign(c, [12])
init = tf.global_variables_initializer()  # for initializing the variables

In [48]:
sess.run([m1,c1])


[array([7]), array([12])]

In [49]:
sess.run(y, feed_dict = {x:7}) ##updated y for new values of m and c.

array([61])